logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'

debug: false
trace: false

server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false