logging:
  level:
    com:
      cognizant: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    root: INFO

debug: false # Enable debug logs.
trace: false # Enable trace logs.

server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: passw0rd
    url: jdbc:mysql://localhost:3307/item?useSSL=false
    username: item
  devtools:
    livereload:
      port: 35731
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

eureka:
  client:
    service-url: 
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://localhost:8761}/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    metadata-map:
      # Adding information about the application GUID and app instance index to 
      # each instance metadata. This will be used for setting the X-CF-APP-INSTANCE header
      # to instruct Go-Router where to route.
      cfAppGuid:       ${vcap.application.application_id}
      cfInstanceIndex: ${INSTANCE_INDEX}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 2

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true