logging:
  level:
    com:
      cognizant: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    root: INFO
server:
  port: 9092
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: passw0rd
    url: jdbc:mysql://localhost:3308/sales-order?useSSL=false
    username: sales-order
  devtools:
    livereload:
      port: 35732
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  rabbitmq:
    host: localhost
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        retry:
          initial-interval: 5000
    username: user
    password: passw0rd
    port: 5672